# Generated by Django 6.0.3 on 2026-03-26 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MPS Loan', max_length=100)),
                ('logo_url', models.URLField(blank=True, help_text='External logo URL (optional)')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('youtube_url', models.URLField(default='https://www.youtube.com/', help_text='YouTube video link for the intro popup')),
                ('bkash_number', models.CharField(default='01XXXXXXXXX', max_length=20)),
                ('nagad_number', models.CharField(default='01XXXXXXXXX', max_length=20)),
                ('rocket_number', models.CharField(default='01XXXXXXXXX', max_length=20)),
                ('interest_rate_min', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('interest_rate_max', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('banner_tagline', models.CharField(default='লোন অফার যেন মিস না হয়!', max_length=200)),
                ('banner_sub', models.CharField(default='চেক করুন mpsloen.com এ', max_length=200)),
                ('security_deposit_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='Security deposit as % of loan amount', max_digits=5)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(choices=[(5000, '৳৫,০০০ টাকা'), (10000, '৳১০,০০০ টাকা'), (15000, '৳১৫,০০০ টাকা'), (20000, '৳২০,০০০ টাকা'), (25000, '৳২৫,০০০ টাকা'), (30000, '৳৩০,০০০ টাকা'), (50000, '৳৫০,০০০ টাকা')], default=5000)),
                ('duration_months', models.IntegerField(choices=[(3, '৩ মাস'), (6, '৬ মাস'), (12, '১২ মাস')], default=3)),
                ('purpose', models.CharField(choices=[('business', 'ব্যবসা'), ('education', 'শিক্ষা'), ('medical', 'চিকিৎসা'), ('personal', 'ব্যক্তিগত'), ('other', 'অন্যান্য')], default='business', max_length=30)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nid_front', models.ImageField(blank=True, null=True, upload_to='nid/')),
                ('nid_back', models.ImageField(blank=True, null=True, upload_to='nid/')),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমাণ'), ('approved', 'অনুমোদিত'), ('rejected', 'প্রত্যাখ্যাত'), ('disbursed', 'বিতরণ করা হয়েছে'), ('closed', 'বন্ধ')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'জমা'), ('withdrawal', 'উত্তোলন'), ('loan_disbursement', 'লোন বিতরণ'), ('loan_repayment', 'লোন পরিশোধ')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('bkash', 'বিকাশ'), ('nagad', 'নগদ'), ('rocket', 'রকেট')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('occupation', models.CharField(choices=[('student', 'ছাত্র/ছাত্রী'), ('business', 'ব্যবসা'), ('service', 'চাকরিজীবী'), ('freelancer', 'ফ্রিল্যান্সার'), ('other', 'অন্যান্য')], default='other', max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
